apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  version: 8.5.2
  count: 1
  config:
    log.level: debug
    http.host: 0.0.0.0
#  elasticsearchRef:
#    name: prototype